# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NeumorPhone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  def import_pods
    pod 'HaishinKit'
  end

  # Pods for NeumorPhone

  target 'NeumorPhoneTests' do
    inherit! :search_paths
    import_pods
    # Pods for testing
  end

  target 'NeumorPhoneUITests' do
    # Pods for testing
  end

end
